// <auto-generated />
using System;
using CaseDL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaseDL.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaseEL.Models.AdayCv", b =>
                {
                    b.Property<int>("CvNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CvNo"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Bolum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CvOlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsDetayi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsYeriAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OgrenimBaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OgrenimBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OgrenimDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OkulAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CvNo");

                    b.ToTable("AdayCvler");
                });

            modelBuilder.Entity("CaseEL.Models.Sicil", b =>
                {
                    b.Property<int>("SicilNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SicilNo"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("BaslamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SicilNo");

                    b.ToTable("Siciller");
                });

            modelBuilder.Entity("CaseEL.Models.SicilOgrenim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OgrenimBaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OgrenimBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OgrenimDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OkulAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SicilNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SicilNo");

                    b.ToTable("SicilOgrenimler");
                });

            modelBuilder.Entity("CaseEL.Models.SicilUcret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GecerlilikBaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SicilNo")
                        .HasColumnType("int");

                    b.Property<string>("UcretTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UcretTutari")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SicilNo");

                    b.ToTable("SicilUcretler");
                });

            modelBuilder.Entity("CaseEL.Models.SicilOgrenim", b =>
                {
                    b.HasOne("CaseEL.Models.Sicil", "Sicil")
                        .WithMany()
                        .HasForeignKey("SicilNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sicil");
                });

            modelBuilder.Entity("CaseEL.Models.SicilUcret", b =>
                {
                    b.HasOne("CaseEL.Models.Sicil", "Sicil")
                        .WithMany()
                        .HasForeignKey("SicilNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sicil");
                });
#pragma warning restore 612, 618
        }
    }
}
